baseURL = "https://petchsira.com/"
languageCode = "en-us"
title = "petchsira"
enableEmoji = true
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "petchsira's website"
  copyright = "Copyright © petchsira"
  dark = "auto"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "blog"
    title = "posts"
    url = "/blog"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]

  # Allows HTML in Markdown
  unsafe = true